"""esquema inicial mastercook

Revision ID: 6ff0a6185b41
Revises: 
Create Date: 2026-05-24 11:50:09.506702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff0a6185b41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('rfc', sa.String(), nullable=True),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_rfc'), 'empresas', ['rfc'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido_paterno', sa.String(), nullable=True),
    sa.Column('apellido_materno', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_table('unidades_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('abreviatura', sa.String(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abreviatura'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_unidades_medida_id'), 'unidades_medida', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('rfc', sa.String(), nullable=True),
    sa.Column('razon_social', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_empresa_id'), 'clientes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_persona_id'), 'clientes', ['persona_id'], unique=False)
    op.create_index(op.f('ix_clientes_rfc'), 'clientes', ['rfc'], unique=False)
    op.create_table('conversiones_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidad_origen_id', sa.Integer(), nullable=False),
    sa.Column('unidad_destino_id', sa.Integer(), nullable=False),
    sa.Column('factor_multiplicador', sa.Float(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['unidad_destino_id'], ['unidades_medida.id'], ),
    sa.ForeignKeyConstraint(['unidad_origen_id'], ['unidades_medida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidad_origen_id', 'unidad_destino_id', name='uq_conversion_par')
    )
    op.create_index(op.f('ix_conversiones_unidades_id'), 'conversiones_unidades', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_rol_empresa_nombre')
    )
    op.create_index(op.f('ix_roles_empresa_id'), 'roles', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('nombre_login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_persona_id'), 'usuarios', ['persona_id'], unique=False)
    op.create_table('auditorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('hecho_por', sa.Integer(), nullable=False),
    sa.Column('nombre_tabla', sa.String(), nullable=False),
    sa.Column('id_tabla', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(), nullable=False),
    sa.Column('modulo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['hecho_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditorias_empresa_id'), 'auditorias', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_auditorias_hecho_por'), 'auditorias', ['hecho_por'], unique=False)
    op.create_index(op.f('ix_auditorias_id'), 'auditorias', ['id'], unique=False)
    op.create_table('cotizaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('nombre_evento', sa.String(), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(), nullable=False),
    sa.Column('personas_estimadas', sa.Integer(), nullable=False),
    sa.Column('estatus', sa.String(), nullable=True),
    sa.Column('costo_operativo', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_cliente_id'), 'cotizaciones', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_empresa_id'), 'cotizaciones', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_id'), 'cotizaciones', ['id'], unique=False)
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('costo_base', sa.Float(), nullable=False),
    sa.Column('peso_bruto', sa.Float(), nullable=True),
    sa.Column('peso_neto', sa.Float(), nullable=True),
    sa.Column('merma_porcentaje', sa.Float(), nullable=True),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_empresa_id'), 'ingredientes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_ingredientes_id'), 'ingredientes', ['id'], unique=False)
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('procedimiento', sa.Text(), nullable=True),
    sa.Column('rendimiento_porciones', sa.Integer(), nullable=True),
    sa.Column('imagen_url', sa.String(), nullable=True),
    sa.Column('costo_total_calculado', sa.Float(), nullable=True),
    sa.Column('es_subreceta', sa.Boolean(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_empresa_id'), 'recetas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_recetas_id'), 'recetas', ['id'], unique=False)
    op.create_table('representantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('es_legal', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_representantes_empresa_id'), 'representantes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_representantes_id'), 'representantes', ['id'], unique=False)
    op.create_table('usuarios_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'rol_id', name='uq_usuario_rol')
    )
    op.create_index(op.f('ix_usuarios_roles_id'), 'usuarios_roles', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_roles_rol_id'), 'usuarios_roles', ['rol_id'], unique=False)
    op.create_index(op.f('ix_usuarios_roles_usuario_id'), 'usuarios_roles', ['usuario_id'], unique=False)
    op.create_table('cotizaciones_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_porciones', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizaciones.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cotizaciones_detalles_cotizacion_id'), 'cotizaciones_detalles', ['cotizacion_id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_detalles_id'), 'cotizaciones_detalles', ['id'], unique=False)
    op.create_index(op.f('ix_cotizaciones_detalles_receta_id'), 'cotizaciones_detalles', ['receta_id'], unique=False)
    op.create_table('recetas_ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('unidad_medida_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['unidad_medida_id'], ['unidades_medida.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_ingredientes_id'), 'recetas_ingredientes', ['id'], unique=False)
    op.create_index(op.f('ix_recetas_ingredientes_ingrediente_id'), 'recetas_ingredientes', ['ingrediente_id'], unique=False)
    op.create_index(op.f('ix_recetas_ingredientes_receta_id'), 'recetas_ingredientes', ['receta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recetas_ingredientes_receta_id'), table_name='recetas_ingredientes')
    op.drop_index(op.f('ix_recetas_ingredientes_ingrediente_id'), table_name='recetas_ingredientes')
    op.drop_index(op.f('ix_recetas_ingredientes_id'), table_name='recetas_ingredientes')
    op.drop_table('recetas_ingredientes')
    op.drop_index(op.f('ix_cotizaciones_detalles_receta_id'), table_name='cotizaciones_detalles')
    op.drop_index(op.f('ix_cotizaciones_detalles_id'), table_name='cotizaciones_detalles')
    op.drop_index(op.f('ix_cotizaciones_detalles_cotizacion_id'), table_name='cotizaciones_detalles')
    op.drop_table('cotizaciones_detalles')
    op.drop_index(op.f('ix_usuarios_roles_usuario_id'), table_name='usuarios_roles')
    op.drop_index(op.f('ix_usuarios_roles_rol_id'), table_name='usuarios_roles')
    op.drop_index(op.f('ix_usuarios_roles_id'), table_name='usuarios_roles')
    op.drop_table('usuarios_roles')
    op.drop_index(op.f('ix_representantes_id'), table_name='representantes')
    op.drop_index(op.f('ix_representantes_empresa_id'), table_name='representantes')
    op.drop_table('representantes')
    op.drop_index(op.f('ix_recetas_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_empresa_id'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_ingredientes_id'), table_name='ingredientes')
    op.drop_index(op.f('ix_ingredientes_empresa_id'), table_name='ingredientes')
    op.drop_table('ingredientes')
    op.drop_index(op.f('ix_cotizaciones_id'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_empresa_id'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_cliente_id'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    op.drop_index(op.f('ix_auditorias_id'), table_name='auditorias')
    op.drop_index(op.f('ix_auditorias_hecho_por'), table_name='auditorias')
    op.drop_index(op.f('ix_auditorias_empresa_id'), table_name='auditorias')
    op.drop_table('auditorias')
    op.drop_index(op.f('ix_usuarios_persona_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_empresa_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_conversiones_unidades_id'), table_name='conversiones_unidades')
    op.drop_table('conversiones_unidades')
    op.drop_index(op.f('ix_clientes_rfc'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_persona_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_empresa_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_unidades_medida_id'), table_name='unidades_medida')
    op.drop_table('unidades_medida')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_empresas_rfc'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
