"""Agregar imagen_url a ingredientes

Revision ID: d34aeab324f6
Revises: 002make_roles_global
Create Date: 2026-05-26 00:32:41.745753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34aeab324f6'
down_revision: Union[str, Sequence[str], None] = '002make_roles_global'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientes', sa.Column('imagen_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredientes', 'imagen_url')
    # ### end Alembic commands ###
